import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import HeroSection from '@/Components/Home/HeroSection'
import Index from '@/Components/Home/Image-Content/Index'
import { aboutUs, download, emi, parentCo, residential } from '@/Components/Home/Image-Content/Content'
import WhyUs from '@/Components/Home/WhyUs'
import Services from '@/Components/Home/Services'
import HowItWorks from '@/Components/Home/HowItWorks'
import Partners from '@/Components/Home/Partners'
import Testimonials from '@/Components/Home/Testimonials'
import DownloadPopup from '@/Components/DownloadPopup'
import { DownloadContext } from '@/Context'
import { useContext } from 'react'


export default function Home() {
  const { downloadPop } = useContext(DownloadContext);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <HeroSection />
        <Index {...aboutUs} />
        <WhyUs />
        <Services />
        <Index {...residential} />
        <HowItWorks />
        <Index {...emi} />
        <Index {...parentCo} />
        <Index {...download} />
        <Partners />
        <Testimonials />
        {downloadPop ? <DownloadPopup /> : ''}
      </>
    </>
  )
}
